# Generated by Django 2.2 on 2019-07-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brithday',
            field=models.CharField(default='1989-05-18', max_length=20, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='graduate_time',
            field=models.CharField(default='2019-01-01', max_length=20, verbose_name='毕业时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='421123198805182054', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='工程师', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job_2',
            field=models.CharField(default='员工', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job_join_time',
            field=models.CharField(default='2019-01-01', max_length=20, verbose_name='入职时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_number',
            field=models.CharField(default='0001', max_length=10, verbose_name='工作证号'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_time',
            field=models.CharField(default='2019-01-01', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='第一次登陆', max_length=20, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='13788881111', max_length=20, verbose_name='练习方式'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='北京师范大学', max_length=30, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=3, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='team_belong',
            field=models.CharField(default='', max_length=20, verbose_name='所属部分'),
        ),
        migrations.AddField(
            model_name='user',
            name='xue_li',
            field=models.CharField(default='本科', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='zhengzhi_mianmao',
            field=models.CharField(default='群众', max_length=10, verbose_name='政治面貌'),
        ),
        migrations.AddField(
            model_name='user',
            name='zhengzhi_time',
            field=models.CharField(default='2019-01-01', max_length=20),
        ),
    ]
