# Generated by Django 2.2 on 2019-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190704_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(default='工程师', max_length=30, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_time',
            field=models.CharField(default='2019-01-01', max_length=30, verbose_name='获得职务时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_belong',
            field=models.CharField(default='技术部', max_length=20, null=True, verbose_name='所属部分'),
        ),
    ]
