# Generated by Django 2.2.1 on 2019-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciname',
            fields=[
                ('names', models.CharField(max_length=256)),
                ('cinemaCode', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('systemName', models.CharField(max_length=50)),
                ('maoyanId', models.IntegerField()),
                ('taopiaopiaoId', models.IntegerField()),
            ],
            options={
                'verbose_name': '影城名称',
                'verbose_name_plural': '影城名称',
                'ordering': ['names'],
            },
        ),
    ]
