# Generated by Django 2.2 on 2019-07-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20190701_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciname',
            name='readme',
            field=models.TextField(default='', verbose_name='说明'),
        ),
    ]
