# Generated by Django 2.2 on 2019-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_ciname_readme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciname',
            name='readme',
            field=models.TextField(default='not thing', verbose_name='说明'),
        ),
    ]
