# Generated by Django 2.2 on 2019-07-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20190703_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='taopiaopiaoId',
            field=models.IntegerField(default=None, null=True, verbose_name='淘票票id'),
        ),
    ]
